// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: MessageProtobuf.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Message;
@class MessageBody;
@class User;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MessageProtobufRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MessageProtobufRoot : GPBRootObject
@end

#pragma mark - User

typedef GPB_ENUM(User_FieldNumber) {
  User_FieldNumber_Uid = 1,
  User_FieldNumber_Name = 2,
  User_FieldNumber_Avatar = 3,
  User_FieldNumber_Id_p = 4,
  User_FieldNumber_Gender = 5,
  User_FieldNumber_Extension = 6,
};

/**
 * *
 * 基础对象 - 用户信息
 **/
GPB_FINAL @interface User : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *uid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *extension;

@end

#pragma mark - MessageBody

typedef GPB_ENUM(MessageBody_FieldNumber) {
  MessageBody_FieldNumber_Type = 1,
  MessageBody_FieldNumber_Content = 2,
  MessageBody_FieldNumber_Ext = 3,
};

/**
 * *
 * 消息体内容
 **/
GPB_FINAL @interface MessageBody : GPBMessage

/** 消息类型: 参考: com.websiyu.im.sdk.api.enums.MessageTypeEnum */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ext;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_MessageId = 1,
  Message_FieldNumber_RequestId = 2,
  Message_FieldNumber_FromUser = 3,
  Message_FieldNumber_ToUser = 4,
  Message_FieldNumber_MessageBody = 5,
  Message_FieldNumber_MessageSeq = 6,
  Message_FieldNumber_Recalled = 7,
  Message_FieldNumber_BornTime = 8,
};

/**
 * *
 * 聊天消息对象 (和拉取消息接口返回的消息元素内容保持一致, 参考: https://apifox.com/apidoc/project-3925967/api-142639725)
 **/
GPB_FINAL @interface Message : GPBMessage

/** 消息ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

/** 消息发送时, 客户端传入的请求ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

/** 发送方用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) User *fromUser;
/** Test to see if @c fromUser has been set. */
@property(nonatomic, readwrite) BOOL hasFromUser;

/** 接收方用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) User *toUser;
/** Test to see if @c toUser has been set. */
@property(nonatomic, readwrite) BOOL hasToUser;

/** 消息内容 */
@property(nonatomic, readwrite, strong, null_resettable) MessageBody *messageBody;
/** Test to see if @c messageBody has been set. */
@property(nonatomic, readwrite) BOOL hasMessageBody;

/** 消息序号 */
@property(nonatomic, readwrite) int64_t messageSeq;

/** 是否已撤回? 0否,1是 */
@property(nonatomic, readwrite) int32_t recalled;

/** 消息生成时间 */
@property(nonatomic, readwrite) int64_t bornTime;

@end

#pragma mark - SendMessageRequest

typedef GPB_ENUM(SendMessageRequest_FieldNumber) {
  SendMessageRequest_FieldNumber_SessionId = 1,
  SendMessageRequest_FieldNumber_MessageBody = 2,
};

/**
 * *
 * 通过Netty连接服务发送的聊天消息请求
 **/
GPB_FINAL @interface SendMessageRequest : GPBMessage

/** 会话ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** 消息内容 */
@property(nonatomic, readwrite, strong, null_resettable) MessageBody *messageBody;
/** Test to see if @c messageBody has been set. */
@property(nonatomic, readwrite) BOOL hasMessageBody;

@end

#pragma mark - MsgSendResult

typedef GPB_ENUM(MsgSendResult_FieldNumber) {
  MsgSendResult_FieldNumber_Result = 1,
  MsgSendResult_FieldNumber_FailMsg = 2,
  MsgSendResult_FieldNumber_SessionId = 3,
  MsgSendResult_FieldNumber_SessionType = 4,
  MsgSendResult_FieldNumber_FromUid = 5,
  MsgSendResult_FieldNumber_ToUid = 6,
  MsgSendResult_FieldNumber_GroupId = 7,
  MsgSendResult_FieldNumber_Message = 8,
};

/**
 * *
 * 客户端消息发送结果, (消息发送失败时, 由后端主动推送给客户端)
 **/
GPB_FINAL @interface MsgSendResult : GPBMessage

/** 消息发送结果, 参考: com.websiyu.im.sdk.api.enums.MsgSendResultEnum, (0, -1, 第三方业务可在此扩展) */
@property(nonatomic, readwrite) int32_t result;

/** 失败原因 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *failMsg;

/** 会话ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** 会话类型 */
@property(nonatomic, readwrite) int32_t sessionType;

/** 发送方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUid;

/** 接收方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUid;

/** 群组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 消息对象内容 */
@property(nonatomic, readwrite, strong, null_resettable) Message *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - MessageNotify

typedef GPB_ENUM(MessageNotify_FieldNumber) {
  MessageNotify_FieldNumber_Type = 1,
  MessageNotify_FieldNumber_SessionId = 2,
  MessageNotify_FieldNumber_SessionType = 3,
  MessageNotify_FieldNumber_FromUid = 4,
  MessageNotify_FieldNumber_ToUid = 5,
  MessageNotify_FieldNumber_GroupId = 6,
  MessageNotify_FieldNumber_Message = 7,
};

/**
 * *
 * 消息通知 (当有新聊天消息时后端主动推送给客户端)
 **/
GPB_FINAL @interface MessageNotify : GPBMessage

/** 通知类型, 1新聊天消息, 参考类: com.websiyu.im.sdk.api.enums.MessageNotifyTypeEnum */
@property(nonatomic, readwrite) int32_t type;

/** 会话ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

/** 会话类型 */
@property(nonatomic, readwrite) int32_t sessionType;

/** 发送方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fromUid;

/** 接收方 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *toUid;

/** 群组ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *groupId;

/** 消息对象 */
@property(nonatomic, readwrite, strong, null_resettable) Message *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
