#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "NSData+SYIM.h"
#import "NSObject+SYIM.h"
#import "NSString+SYIM.h"
#import "SYIMEnviormentConfig.h"
#import "SYIMOptions.h"
#import "SYIMAuthReqModel.h"
#import "SYIMFindKeyModel.h"
#import "SYIMLoginReqModel.h"
#import "SYIMBaseRequestModel.h"
#import "SYIMBaseResponseModel.h"
#import "SYIMRequestHeader.h"
#import "SYIMContactFriendAddReqModel.h"
#import "SYIMContactFriendDeleteReqModel.h"
#import "SYIMContactFriendInfoReqModel.h"
#import "SYIMContactFriendListReqModel.h"
#import "SYIMContactFriendUpdateReqModel.h"
#import "SYIMContactGetReqModel.h"
#import "SYIMContactUpdateReqModel.h"
#import "SYIMConversationDeleteReqModel.h"
#import "SYIMConversationListReqModel.h"
#import "SYIMConversationOpenSessionReqModel.h"
#import "SYIMConversationUnReadSyncReqModel.h"
#import "SYIMGroupAddReqModel.h"
#import "SYIMGroupDetailReqModel.h"
#import "SYIMGroupExitReqModel.h"
#import "SYIMGroupListReqModel.h"
#import "SYIMGroupMemberReqModel.h"
#import "SYIMMessageGetListReqModel.h"
#import "SYIMMessageRecallModel.h"
#import "SYIMOssConfigReqModel.h"
#import "SYIMHttpManager.h"
#import "SYIMContact.h"
#import "SYIMContactFriendList.h"
#import "SYIMContactManagerImpl.h"
#import "SYIMContactProtocol.h"
#import "SYIMConversation.h"
#import "SYIMConversationGetList.h"
#import "SYIMConversationManagerImpl.h"
#import "SYIMConversationProtocol.h"
#import "SYIMGroup.h"
#import "SYIMGroupManagerImpl.h"
#import "SYIMGroupProtocol.h"
#import "SYIMMessageBody.h"
#import "SYIMMessage.h"
#import "SYIMMessageGetList.h"
#import "SYIMChatManagerImpl.h"
#import "SYIMMessageProtocol.h"
#import "SYIMOSSConfig.h"
#import "SYIMOSSManager.h"
#import "SYIMManagerProtocol.h"
#import "SYIMAuthInfo.h"
#import "SYIMSessionManagerImpl.h"
#import "SYIMSessionProtocol.h"
#import "SYIMContactDao.h"
#import "SYIMConversationDao.h"
#import "SYIMMessageDao.h"
#import "SYIMSessionDao.h"
#import "SYIMDBManager.h"
#import "SYIMDBProtocols.h"
#import "SYIMSocketClient.h"
#import "SYIMSocketMessage.h"
#import "SYIMSocketMessageDecoder.h"
#import "SYIMSocketMessageEncoder.h"
#import "SYIMMessageEncryption.h"
#import "SYIMClientManager.h"
#import "SYIMSocketProtocol.h"
#import "SYIM.h"
#import "SYIMManager.h"
#import "SYIMGlobalEnum.h"
#import "SYIMLogManager.h"
#import "SYIMMacro.h"
#import "SYIMSessionUtil.h"
#import "SYIMSm4Util.h"
#import "MessageProtobuf.pbobjc.h"
#import "OuterProtocol.pbobjc.h"

FOUNDATION_EXPORT double SYIMVersionNumber;
FOUNDATION_EXPORT const unsigned char SYIMVersionString[];

