// Generated by the protocol buffer compiler.  DO NOT EDIT!
// clang-format off
// source: OuterProtocol.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Authentication;
@class AuthenticationInform;
@class Notify;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum AuthenticationResultType

/** login通知类型，0：登录成功  1：登录失败，token失效  2：强制下线，被其他人挤占 3：限制登录 */
typedef GPB_ENUM(AuthenticationResultType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AuthenticationResultType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AuthenticationResultType_Success = 0,
  AuthenticationResultType_Fail = 1,
  AuthenticationResultType_ForcedOffline = 2,
  AuthenticationResultType_Restricted = 3,
};

GPBEnumDescriptor *AuthenticationResultType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AuthenticationResultType_IsValidValue(int32_t value);

#pragma mark - Enum Type

/** 外层协议类型 */
typedef GPB_ENUM(Type) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Type_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Type_Ack = 0,
  Type_Message = 1,
  Type_Login = 2,
  Type_Notify = 3,
};

GPBEnumDescriptor *Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Type_IsValidValue(int32_t value);

#pragma mark - OuterProtocolRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface OuterProtocolRoot : GPBRootObject
@end

#pragma mark - Protocol_Class

typedef GPB_ENUM(Protocol_Class_FieldNumber) {
  Protocol_Class_FieldNumber_Type = 1,
  Protocol_Class_FieldNumber_RequestId = 2,
  Protocol_Class_FieldNumber_Data_p = 3,
  Protocol_Class_FieldNumber_Authentication = 5,
  Protocol_Class_FieldNumber_AuthenticationInform = 6,
  Protocol_Class_FieldNumber_Notify = 7,
};

typedef GPB_ENUM(Protocol_Class_Content_OneOfCase) {
  Protocol_Class_Content_OneOfCase_GPBUnsetOneOfCase = 0,
  Protocol_Class_Content_OneOfCase_Data_p = 3,
  Protocol_Class_Content_OneOfCase_Authentication = 5,
  Protocol_Class_Content_OneOfCase_AuthenticationInform = 6,
  Protocol_Class_Content_OneOfCase_Notify = 7,
};

GPB_FINAL @interface Protocol_Class : GPBMessage

/** 类型 */
@property(nonatomic, readwrite) Type type;

/** 请求id，客户端唯一 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

/** 数据 */
@property(nonatomic, readonly) Protocol_Class_Content_OneOfCase contentOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSData *data_p;

@property(nonatomic, readwrite, strong, null_resettable) Authentication *authentication;

@property(nonatomic, readwrite, strong, null_resettable) AuthenticationInform *authenticationInform;

@property(nonatomic, readwrite, strong, null_resettable) Notify *notify;

@end

/**
 * Fetches the raw value of a @c Protocol_Class's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Protocol_Class_Type_RawValue(Protocol_Class *message);
/**
 * Sets the raw value of an @c Protocol_Class's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetProtocol_Class_Type_RawValue(Protocol_Class *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'content'.
 **/
void Protocol_Class_ClearContentOneOfCase(Protocol_Class *message);

#pragma mark - Authentication

typedef GPB_ENUM(Authentication_FieldNumber) {
  Authentication_FieldNumber_Token = 1,
  Authentication_FieldNumber_AppId = 2,
  Authentication_FieldNumber_DeiceType = 3,
};

/**
 * 客户端身份认证发送数据
 **/
GPB_FINAL @interface Authentication : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite) int32_t deiceType;

@end

#pragma mark - AuthenticationInform

typedef GPB_ENUM(AuthenticationInform_FieldNumber) {
  AuthenticationInform_FieldNumber_Result = 1,
};

/**
 * 服务端登录相关通知
 **/
GPB_FINAL @interface AuthenticationInform : GPBMessage

@property(nonatomic, readwrite) AuthenticationResultType result;

@end

/**
 * Fetches the raw value of a @c AuthenticationInform's @c result property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AuthenticationInform_Result_RawValue(AuthenticationInform *message);
/**
 * Sets the raw value of an @c AuthenticationInform's @c result property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAuthenticationInform_Result_RawValue(AuthenticationInform *message, int32_t value);

#pragma mark - Notify

typedef GPB_ENUM(Notify_FieldNumber) {
  Notify_FieldNumber_SessionId = 1,
};

/**
 * 会话拉取通知
 **/
GPB_FINAL @interface Notify : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
